In [27]:
print('Hello world')

Hello world


In [28]:
# LOGISTIC REGRESSION:- of 3 types
#1 Binary
#2 Nominal
#3 Ordinal

In [29]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report , confusion_matrix

In [31]:
# Here, the prediction would be a probability case.
# So, x varibale could have whatever data
# y-variable would have only 2 values(0 and 1)

x=np.arange(10)
y=np.random.randint(0,2,10)

print(f'Variables = {x}\n')
print(f'prediction data = {y}')

x=x.reshape(-1,1)
y=y.reshape(-1,1)


Variables = [0 1 2 3 4 5 6 7 8 9]

prediction data = [1 0 0 0 0 1 0 1 1 1]


In [32]:
model=LogisticRegression(solver='liblinear',C=10.0,random_state=0)
model.fit(x,y)

c:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [33]:
print(model.coef_)
print(model.intercept_)

[[0.31744116]]
[-1.36303623]


In [34]:
probability=model.predict_proba(x) # First value--- prob. of 0 and Second one is prob. of 1
y_pred=model.predict(x)

print(probability,'\n')
print(y_pred)

[[0.79625272 0.20374728]
 [0.73992813 0.26007187]
 [0.67440003 0.32559997]
 [0.60125877 0.39874123]
 [0.52330101 0.47669899]
 [0.44419112 0.55580888]
 [0.36781296 0.63218704]
 [0.29753747 0.70246253]
 [0.23568334 0.76431666]
 [0.18333196 0.81666804]] 

[0 0 0 0 0 1 1 1 1 1]


In [36]:
model.score(x,y)

0.8

In [38]:
# Tells abou the accuracy
# [[TP,FP
#   FN,TN]]    TP- True Positive, FN- False Negative
confusion_matrix(y,y_pred)

array([[4, 1],
       [1, 4]], dtype=int64)

In [43]:
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.80      0.80         5
           1       0.80      0.80      0.80         5

    accuracy                           0.80        10
   macro avg       0.80      0.80      0.80        10
weighted avg       0.80      0.80      0.80        10

